apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fabric-app
  namespace: default
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubernetes
    repoURL: https://github.com/drososkats/fabric-smart-warehouse.git
    targetRevision: main
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true

