apiVersion: apps/v1
kind: Deployment
metadata:
  name: fabric-backend
  labels:
    app: fabric-backend
    tier: backend
    env: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fabric-backend
  template:
    metadata:
      labels:
       app: fabric-backend
       tier: backend
       env: development
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "fabric-backend"
        vault.hashicorp.com/agent-inject-secret-config: "secret/data/fabric"
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "secret/data/fabric" -}}
          {
            "mongo_uri": "{{ .Data.data.mongo_uri }}",
            "minio_access_key": "{{ .Data.data.minio_access_key }}",
            "minio_secret_key": "{{ .Data.data.minio_secret_key }}"
          }
          {{- end -}} 
    spec:
      containers:
      - name: backend
        image: katsdros/fabric-backend:v48
        imagePullPolicy: Always
        securityContext:             
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
        # internal settings
        - name: PORT
          value: "5000"
        - name: RABBITMQ_URI
          value: "amqp://guest:guest@rabbitmq-service:5672"
        - name: MINIO_ENDPOINT
          value: "minio-service"
        - name: MINIO_PORT
          value: "9000"
        - name: MINIO_ACCESS_KEY
          value: "admin"
        
        # bucket name
        - name: MINIO_BUCKET
          value: "products"

        # external access
        - name: VM_IP
          value: "20.188.60.198"

        # database
        - name: appName
          value: "ClusterFabric"
---
apiVersion: v1
kind: Service
metadata:
  name: fabric-backend-service
spec:
  selector:
    app: fabric-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
