apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend-deployment.yaml
  - backend-hpa.yaml
  - frontend-deployment.yaml
  - minio-deployment.yaml
  - nodered-deployment.yaml
  - rabbitmq-deployment.yaml
  - thingsboard-deployment.yaml
  - thumbnail-deployment.yaml
